### ISSUE TITLE
Waves stop spawning after defeating the first boss

### ISSUE THREAD

**Issue by sp4ceforc3** [sp4ceforc3/SpaceShooter#42]

**Comment by sp4ceforc3** [comment]
it is connected to the errors produced by the boss. Other boss functions as expected

**Comment by domai-tb** [comment]
Some weird thing happens with the WaveHandler. The new wave spawning works fine, when the prefab is used manually, but totally messed up with the WaveHandler. Also the destruction of the Bosses doesn't work anymore. Strange Thing: It just happens when using the WaveHandler. The Prefab itself looks fine. 

Also, I was not able to repeat your error messages. I don't have any error messages at all when playing the game normally (without godmode and crashing in the enemies).

**Comment by sp4ceforc3** [comment]
Sprite renderer Error Message should be fixed by my refactoring/adjustment with Vererbung.

Godmode was fixed by me in different issue #44

**Comment by sp4ceforc3** [comment]
So tue generall Problem lies in the prefab?

Maybe deleting it and creating it anew from the scene fixes the wierd behaviour 🤔🤔

**Comment by domai-tb** [comment]
No, I already fixed it. The problem was caused by the Start-Function you added in DomaiBoss.cs. Probaly a weird issue of C# / Unity and how they handle it

**Comment by sp4ceforc3** [comment]
Lol, I added IT in a try to fix the Problem. Wtf ist going on....

**Comment by sp4ceforc3** [comment]
xD
